# debug: true
server:
  port: 8888
mybatis:
  type-aliases-package: com.trd.oecms.entity
  mapper-locations:
    - mybatis/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          # DataSource类型
    driver-class-name: com.mysql.jdbc.Driver              # MySQL驱动器
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/oecms?characterEncoding=utf8&useSSL=false
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
logging:
  level:
    com.trd.oecms.dao: debug # 打开日志，查看sql语句
